# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Data Science Academy
author: STRV, Data Science Department
logo: static/images/logo.png
copyright: "2022"
# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns: [ _build, Thumbs.db, .DS_Store, environment.yml, README.md, LICENSE ]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/strvcom/ds-academy
  branch: master
  path_to_book: ""

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  baseurl: https://strvcom.github.io/ds-academy/intro.html
